{{- $ref := ( dict "root" . "name" "database" ) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "iofog.name" $ref }}
  labels:
    {{ include "iofog.labels" $ref | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
